import { RoomType } from "@/types";

export const rooms: RoomType[] = [
  {
    id: "ocean-pool-villa",
    type: "room",
    category: "1-7 독채",
    name: "해수풀빌라",
    roomNumbers: [
      { id: "101", maxNights: 14 },
      { id: "102", maxNights: 14 },
      { id: "103", maxNights: 10 },
      { id: "104", maxNights: 10 },
      { id: "105", maxNights: 7 },
      { id: "106", maxNights: 7 },
      { id: "107", maxNights: 7 },
    ],
    roomConfig: "방 2 · 욕실 · 주방 · 테라스",
    bedCount: "2개",
    capacity: "4인",
    maxCapacity: "최대 6인",
    baseGuests: 4,
    maxGuests: 6,
    petAllowed: true,
    petLimit: "최대 2마리",
    maxPets: 2,
    checkIn: "15:00",
    checkOut: "11:00",
    price: 450000,
    weekendPrice: 550000,
    peakPrice: 650000,
    extraPersonFee: 30000,
    petFee: 20000,
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    amenities: ["해수 수영장", "테라스", "주방", "에어컨", "TV", "Wi-Fi", "욕조"],
    description: "전 객실에서 오션뷰를 감상할 수 있으며, 전용 야외발코니에서 프라이빗 요리를 즐길 수 있습니다.",
  },
  {
    id: "ocean-condo-standard",
    type: "room",
    category: "콘도형",
    name: "오션 콘도 스탠다드",
    roomNumbers: [
      { id: "201", maxNights: 14 },
      { id: "202", maxNights: 14 },
      { id: "203", maxNights: 10 },
      { id: "204", maxNights: 7 },
      { id: "205", maxNights: 7 },
    ],
    roomConfig: "방 · 욕실 · 주방 · 테라스",
    bedCount: "1개",
    capacity: "2인",
    maxCapacity: "최대 4인",
    baseGuests: 2,
    maxGuests: 4,
    petAllowed: false,
    checkIn: "15:00",
    checkOut: "11:00",
    price: 180000,
    weekendPrice: 220000,
    peakPrice: 280000,
    extraPersonFee: 25000,
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    amenities: ["테라스", "주방", "에어컨", "TV", "Wi-Fi"],
    description: "오션뷰와 함께하는 아늑한 콘도형 객실입니다.",
  },
  {
    id: "ocean-condo-deluxe",
    type: "room",
    category: "콘도형",
    name: "오션 콘도 디럭스",
    roomNumbers: [
      { id: "301", maxNights: 14 },
      { id: "302", maxNights: 14 },
      { id: "303", maxNights: 10 },
      { id: "304", maxNights: 7 },
    ],
    roomConfig: "방 · 욕실 · 주방 · 테라스",
    bedCount: "2개",
    capacity: "4인",
    maxCapacity: "최대 6인",
    baseGuests: 4,
    maxGuests: 6,
    petAllowed: false,
    checkIn: "15:00",
    checkOut: "11:00",
    price: 280000,
    weekendPrice: 350000,
    peakPrice: 420000,
    extraPersonFee: 30000,
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    amenities: ["테라스", "주방", "에어컨", "TV", "Wi-Fi", "욕조"],
    description: "넓은 공간에서 가족과 함께 편안한 휴식을 즐기세요.",
  },
  {
    id: "sunset-camping-house",
    type: "room",
    category: "캠핑하우스",
    name: "선셋 캠핑하우스",
    roomNumbers: [
      { id: "캠핑하우스1", maxNights: 7 },
      { id: "캠핑하우스2", maxNights: 7 },
      { id: "캠핑하우스3", maxNights: 5 },
    ],
    roomConfig: "방 2 · 욕실 · 주방 · 테라스",
    bedCount: "2개",
    capacity: "4인",
    maxCapacity: "최대 6인",
    baseGuests: 4,
    maxGuests: 6,
    petAllowed: true,
    petLimit: "최대 2마리",
    maxPets: 2,
    checkIn: "15:00",
    checkOut: "11:00",
    price: 200000,
    weekendPrice: 250000,
    peakPrice: 300000,
    extraPersonFee: 25000,
    petFee: 15000,
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    amenities: ["테라스", "바베큐", "주방", "에어컨", "Wi-Fi"],
    description: "석양을 바라보며 캠핑의 낭만을 즐길 수 있는 하우스입니다.",
  },
];

export function getRoomById(id: string): RoomType | undefined {
  return rooms.find(room => room.id === id);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('ko-KR').format(price);
}
