import { SiteData } from "@/types"

export const siteData: SiteData[] = [
  {
    id: "S",
    title: "S 사이트",
    features: ["바다 바로 앞 데크", "최적의오션뷰", "반려견 가능(S1 & S2)"],
    imageQuery: "serene campsite by the rocky shore at sunset",
    disallowed: ["차박", "카라반", "캠핑카", "루프탑"],
    image: "/images/site/s.jpg",
  },
  {
    id: "A",
    title: "A 사이트",
    features: ["바닷가 솔숲 평지 데크 or 파쇄석", "2해변 인접", "반려견 동반 가능"],
    imageQuery: "cozy tent in a pine forest near the beach",
    disallowed: ["차박", "카라반", "캠핑카", "루프탑"],
    image: "/images/site/a.jpg",
  },
  {
    id: "B",
    title: "B 사이트",
    features: ["해변 평지 파쇄석", "2해변 & 공용수영장 인접"],
    imageQuery: "family campsite near a swimming pool and beach",
    allowed: ["카라반", "캠핑카", "차박", "루프탑"],
    image: "/images/site/b.jpg",
  },
  {
    id: "C",
    title: "C 사이트",
    features: ["해변 평지 파쇄석", "1해변 & 독살체험장 인접"],
    imageQuery: "campsite on a flat area next to a calm beach",
    allowed: ["카라반", "캠핑카", "차박", "루프탑"],
    image: "/images/site/c.jpg",
  },
  {
    id: "D",
    title: "D 사이트",
    features: ["중앙 평지 파쇄석", "영유아 & 어르신 추천"],
    imageQuery: "accessible flat campsite with easy access",
    allowed: ["카라반", "캠핑카", "차박", "루프탑"],
    image: "/images/site/d.jpg",
  },
  {
    id: "E",
    title: "E 사이트",
    features: ["중앙 평지 파쇄석", "영유아 & 어르신 추천"],
    imageQuery: "spacious central campsite suitable for small caravans",
    allowed: ["카라반", "캠핑카", "차박", "루프탑"],
    image: "/images/site/e.jpg",
  },
  {
    id: "F",
    title: "F 사이트",
    features: ["바닷가 솔숲 데크", "1해변 & 독살체험장 인접"],
    imageQuery: "tent on a terrace in a pine forest overlooking the sea",
    image: "/images/site/f.jpg",
  },
  {
    id: "G",
    title: "G 사이트",
    features: ["바닷가 솔숲 데크", "1해변 & 독살체험장 인접"],
    imageQuery: "hammock between pine trees at a campsite with sea view",
    image: "/images/site/g.jpg",
  },
  {
    id: "H",
    title: "H 사이트",
    features: ["중앙 평지 파쇄석", "2가족 이용 추천"],
    imageQuery: "two tents set up for a group on a flat grassy area",
    image: "/images/site/h.jpg",
  },
  {
    id: "K",
    title: "K 사이트",
    features: ["파쇄석 사이트", "탁트인 오션뷰 & 낙조", "K3 - 5"],
    imageQuery: "simple gravel campsite area with basic amenities",
    allowed: ["카라반", "캠핑카", "차박", "루프탑"],
    image: "/images/site/k.jpg",
  },
  {
    id: "전망",
    title: "전망 사이트",
    features: ["독립된 파쇄석", "탁 트인 오션뷰 & 낙조", "전망 14 - 17"],
    imageQuery: "wooden deck campsite with a panoramic ocean sunset view",
    image: "/images/site/view_site.jpg",
  },
  {
    id: "반려견",
    title: "반려견 캠핑장",
    features: ["솔숲 파쇄석", "탁트인 오션뷰 & 낙조", "반려견 전용"],
    imageQuery: "happy dog playing at a dedicated pet-friendly campsite",
    allowed: ["차박", "루프탑"],
    image: "/images/site/pet_site.jpg",
  },
]

export const siteCategories = ["All", "S", "A", "B", "C", "D", "E", "F", "G", "H", "K", "전망", "반려견"]